# Generated by Django 3.0.8 on 2020-07-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biao4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psxh', models.CharField(max_length=20)),
                ('lyxh', models.CharField(max_length=20)),
                ('lyname', models.CharField(max_length=100)),
                ('lbxh', models.CharField(max_length=20)),
                ('lb', models.CharField(max_length=100)),
                ('dxxh', models.CharField(max_length=20)),
                ('duixiang', models.CharField(max_length=100)),
                ('xmxh', models.CharField(max_length=20)),
                ('xmmc', models.CharField(max_length=100)),
                ('csmc', models.CharField(max_length=100)),
                ('yjbz', models.CharField(max_length=300)),
                ('xzfw', models.CharField(max_length=100)),
                ('sm', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
