# Generated by Django 2.0 on 2020-08-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bpsdwxx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jyjcjgmc', models.CharField(max_length=100, verbose_name='检验检测机构名称')),
                ('zcdz', models.CharField(max_length=100, verbose_name='注册地址')),
            ],
            options={
                'verbose_name': '被评审单位信息表',
                'verbose_name_plural': '被评审单位信息表',
            },
        ),
    ]
