# Generated by Django 3.1.2 on 2020-11-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pingshenxxb',
            old_name='uid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='importfile',
            name='importtype',
            field=models.CharField(choices=[('0', '0_读取评审通知(docx格式)'), ('3', '3_现场评审核查表(docx格式)'), ('1', '1_读取评审报告(docx格式)'), ('2', '2_评审员信息表格(docx格式)')], default=0, max_length=1, verbose_name='导入类型'),
        ),
    ]
