# Generated by Django 3.0.7 on 2020-07-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biao4',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('psxh', models.CharField(max_length=20)),
                ('lyxh', models.CharField(max_length=20)),
                ('lyname', models.CharField(max_length=50)),
                ('lbxh', models.CharField(max_length=20)),
                ('lb', models.CharField(max_length=50)),
                ('dxxh', models.CharField(max_length=20)),
                ('duixiang', models.CharField(max_length=50)),
                ('xmxh', models.CharField(max_length=20)),
                ('xmmc', models.CharField(max_length=50)),
                ('csmc', models.CharField(max_length=50)),
                ('yjbz', models.CharField(max_length=100)),
                ('xzfw', models.CharField(max_length=100)),
                ('sm', models.CharField(max_length=50)),
            ],
        ),
    ]
