# Generated by Django 2.0 on 2020-08-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='importtype',
            field=models.CharField(choices=[('2', '2_评审员信息表格(docx格式)'), ('0', '0_读取评审通知(docx格式)'), ('1', '1_读取评审报告(docx格式)')], max_length=1, verbose_name='导入类型'),
        ),
    ]
