# Generated by Django 3.1.2 on 2020-10-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('realname', models.CharField(max_length=10, verbose_name='真名')),
            ],
            options={
                'verbose_name': '用户信息表',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.AlterField(
            model_name='importfile',
            name='importtype',
            field=models.CharField(choices=[('0', '0_读取评审通知(docx格式)'), ('2', '2_评审员信息表格(docx格式)'), ('1', '1_读取评审报告(docx格式)'), ('3', '3_现场评审核查表(docx格式)')], default=0, max_length=1, verbose_name='导入类型'),
        ),
        migrations.AddField(
            model_name='pingshenxxb',
            name='userinfo',
            field=models.ManyToManyField(to='Myapp.UserInfo'),
        ),
    ]
