# Generated by Django 2.0 on 2020-08-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='file',
            field=models.FileField(upload_to='File', verbose_name='文件名'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='importtype',
            field=models.CharField(choices=[('0', '读取评审通知'), ('1', '读取评审报告'), ('2', '评审员信息表格')], max_length=1, verbose_name='导入类型'),
        ),
        migrations.AlterField(
            model_name='pszcy',
            name='psydtl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.PsyuanDetail', verbose_name='评审员信息号'),
        ),
    ]
