# Generated by Django 2.0 on 2020-08-14 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pszcy',
            name='psydtl',
        ),
    ]
