# Generated by Django 2.0 on 2020-08-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='File', verbose_name='上传文件')),
                ('name', models.CharField(max_length=50, verbose_name='文件名')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='biao4',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='biao4',
            name='lyname',
            field=models.CharField(max_length=100, verbose_name='领域名称'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='psxh',
            field=models.CharField(max_length=20, verbose_name='评审编号'),
        ),
    ]
