# Generated by Django 3.0.7 on 2020-08-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pingshenxxb',
            name='psyh',
        ),
        migrations.RemoveField(
            model_name='psyuanb',
            name='psy_detail',
        ),
        migrations.AlterField(
            model_name='biao72',
            name='bdjg',
            field=models.BooleanField(default=False, verbose_name='利用实验室间比对结果'),
        ),
        migrations.AlterField(
            model_name='biao72',
            name='clsh',
            field=models.BooleanField(default=False, verbose_name='测量审核盲样试验'),
        ),
        migrations.AlterField(
            model_name='biao72',
            name='cyjlbg',
            field=models.BooleanField(default=False, verbose_name='查阅记录和报告'),
        ),
        migrations.AlterField(
            model_name='biao72',
            name='hcyq',
            field=models.BooleanField(default=False, verbose_name='核查仪器设备配置'),
        ),
        migrations.AlterField(
            model_name='biao72',
            name='nlyz',
            field=models.BooleanField(default=False, verbose_name='利用能力验证结果'),
        ),
        migrations.AlterField(
            model_name='biao72',
            name='sfqr',
            field=models.BooleanField(default=False, verbose_name='是否确认(Y/N)'),
        ),
        migrations.AlterField(
            model_name='biao72',
            name='xcsy',
            field=models.BooleanField(default=False, verbose_name='现场试验'),
        ),
        migrations.AlterField(
            model_name='biao72',
            name='xctw',
            field=models.BooleanField(default=False, verbose_name='现场提问'),
        ),
        migrations.AlterField(
            model_name='biao72',
            name='xcys',
            field=models.BooleanField(default=False, verbose_name='现场演示'),
        ),
    ]
