# Generated by Django 2.0 on 2020-08-15 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pszcy',
            old_name='psxxb',
            new_name='psxxbs',
        ),
        migrations.AlterField(
            model_name='pszcy',
            name='psydtl',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.PsyuanDetail', verbose_name='评审员信息号'),
        ),
    ]
