# Generated by Django 3.0.7 on 2020-07-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biao4',
            name='yjbz',
            field=models.CharField(max_length=200),
        ),
    ]
