# Generated by Django 3.0.7 on 2020-07-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20200703_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biao4',
            name='sm',
            field=models.CharField(max_length=200),
        ),
    ]
