# Generated by Django 2.0 on 2020-08-24 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Myapp', '0002_auto_20200823_2204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pingshenxxb',
            options={'verbose_name': '评审任务信息总表', 'verbose_name_plural': '评审任务信息总表'},
        ),
        migrations.AlterModelOptions(
            name='psyuandetail',
            options={'verbose_name': '评审员个人信息表', 'verbose_name_plural': '评审员个人信息表'},
        ),
        migrations.AlterModelOptions(
            name='pszcy',
            options={'verbose_name': '评审组名单', 'verbose_name_plural': '评审组名单'},
        ),
        migrations.AddField(
            model_name='pingshenxxb',
            name='bpsdwxx',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.Bpsdwxx', verbose_name='被评审单位Id'),
        ),
        migrations.AddField(
            model_name='pingshenxxb',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户Id'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='importtype',
            field=models.CharField(choices=[('2', '评审员信息表格'), ('0', '读取评审通知'), ('1', '读取评审报告')], max_length=1, verbose_name='导入类型'),
        ),
    ]
