# Generated by Django 2.0 on 2020-08-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20200807_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biao5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('ziwuzicheng', models.CharField(max_length=30)),
                ('sqqzly', models.CharField(max_length=500)),
                ('beizu', models.CharField(max_length=300)),
            ],
        ),
    ]
