# Generated by Django 3.1.1 on 2020-09-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20200824_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importfile',
            options={'verbose_name': '从文件导入数据', 'verbose_name_plural': '从文件导入数据'},
        ),
        migrations.AlterField(
            model_name='importfile',
            name='importtype',
            field=models.CharField(choices=[('0', '0_读取评审通知(docx格式)'), ('1', '1_读取评审报告(docx格式)'), ('2', '2_评审员信息表格(docx格式)')], default=0, max_length=1, verbose_name='导入类型'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='psxxb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.pingshenxxb', verbose_name='评审信息ID'),
        ),
    ]
