# Generated by Django 2.0 on 2020-08-09 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_biao5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pingshenxxb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pstzh', models.CharField(max_length=30, verbose_name='评审通知编号')),
            ],
            options={
                'verbose_name': '评审信息总表',
                'verbose_name_plural': '评审信息总表',
            },
        ),
        migrations.CreateModel(
            name='Psyuanxxb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='姓名')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('danwei', models.CharField(max_length=100, verbose_name='工作单位')),
                ('psybh', models.CharField(max_length=15, verbose_name='评审员编号')),
            ],
            options={
                'verbose_name': '评审员名单表',
                'verbose_name_plural': '评审员名单表',
            },
        ),
        migrations.AlterModelOptions(
            name='biao4',
            options={'ordering': ['id'], 'verbose_name': '建议批准的检验检测能力表 表4', 'verbose_name_plural': '建议批准的检验检测能力表 表4'},
        ),
        migrations.AlterModelOptions(
            name='biao5',
            options={'verbose_name': '建议批准的授权签字人 表5', 'verbose_name_plural': '建议批准的授权签字人 表5'},
        ),
        migrations.AlterModelOptions(
            name='importfile',
            options={'ordering': ['name'], 'verbose_name': '文件输入列表', 'verbose_name_plural': '文件输入列表'},
        ),
        migrations.RemoveField(
            model_name='biao4',
            name='psxh',
        ),
        migrations.AlterField(
            model_name='biao4',
            name='csmc',
            field=models.CharField(max_length=100, verbose_name='参数名称'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='duixiang',
            field=models.CharField(max_length=100, verbose_name='检测对象'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='dxxh',
            field=models.CharField(max_length=20, verbose_name='对象序号'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='lb',
            field=models.CharField(max_length=100, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='lbxh',
            field=models.CharField(max_length=20, verbose_name='类别序号'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='lyname',
            field=models.CharField(max_length=100, verbose_name='领域'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='lyxh',
            field=models.CharField(max_length=20, verbose_name='领域序号'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='sm',
            field=models.CharField(max_length=200, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='xmmc',
            field=models.CharField(max_length=100, verbose_name='参数名称'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='xmxh',
            field=models.CharField(max_length=20, verbose_name='参数序号'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='xzfw',
            field=models.CharField(max_length=100, verbose_name='限制范围'),
        ),
        migrations.AlterField(
            model_name='biao4',
            name='yjbz',
            field=models.CharField(max_length=300, verbose_name='依据的标准（方法）名称及编号（含年号）'),
        ),
        migrations.AlterField(
            model_name='biao5',
            name='beizu',
            field=models.CharField(max_length=300, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='biao5',
            name='name',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='biao5',
            name='sqqzly',
            field=models.CharField(max_length=500, verbose_name='授权签字领域'),
        ),
        migrations.AlterField(
            model_name='biao5',
            name='ziwuzicheng',
            field=models.CharField(max_length=30, verbose_name='职务/职称'),
        ),
        migrations.AddField(
            model_name='pingshenxxb',
            name='psyh',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Psyuanxxb'),
        ),
    ]
