# Generated by Django 3.1.2 on 2020-11-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_auto_20201105_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xcpshcb',
            name='psjg',
        ),
        migrations.RemoveField(
            model_name='xcpshcb',
            name='pssm',
        ),
        migrations.RemoveField(
            model_name='xcpshcb',
            name='psyj',
        ),
        migrations.AlterField(
            model_name='bfhxiang',
            name='bfsqueren',
            field=models.CharField(choices=[('1', '不确认'), ('0', '确认')], default=0, max_length=1, verbose_name='被评审方确认意见'),
        ),
        migrations.AlterField(
            model_name='bfhxiang',
            name='jielun',
            field=models.CharField(choices=[('0', '不符合'), ('1', '不适用')], default=0, max_length=10, verbose_name='评审结果'),
        ),
        migrations.AlterField(
            model_name='bfhxiang',
            name='qrfs',
            field=models.CharField(choices=[('2', '其他'), ('0', '提供必要的见证材料'), ('1', '现场跟踪访问')], default=0, max_length=1, verbose_name='确认方式'),
        ),
        migrations.AlterField(
            model_name='bfhxiang',
            name='zzqueren',
            field=models.CharField(choices=[('1', '不确认'), ('0', '确认')], default=0, max_length=1, verbose_name='评审组长确认意见'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='importtype',
            field=models.CharField(choices=[('1', '1_读取评审报告(docx格式)'), ('2', '2_评审员信息表格(docx格式)'), ('3', '3_现场评审核查表(docx格式)'), ('0', '0_读取评审通知(docx格式)')], default=0, max_length=1, verbose_name='导入类型'),
        ),
    ]
