# Generated by Django 3.1.1 on 2020-09-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_auto_20200907_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='importtype',
            field=models.CharField(choices=[('0', '0_读取评审通知(docx格式)'), ('2', '2_评审员信息表格(docx格式)'), ('1', '1_读取评审报告(docx格式)')], default=0, max_length=1, verbose_name='导入类型'),
        ),
        migrations.CreateModel(
            name='Xcpshcb71',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhangbh', models.CharField(max_length=3, verbose_name='条款章号')),
                ('zhangmc', models.CharField(max_length=8, verbose_name='条款章名')),
                ('tkhao', models.CharField(max_length=10, verbose_name='条款号')),
                ('psneirong', models.CharField(max_length=1000, verbose_name='评审内容')),
                ('psjg', models.CharField(max_length=1, verbose_name='评审结果')),
                ('pssm', models.CharField(max_length=500, verbose_name='评审说明')),
                ('psxxbs', models.ManyToManyField(to='Myapp.Pingshenxxb', verbose_name='评审通知号')),
            ],
            options={
                'verbose_name': '检验检测机构资质认定现场评审核查表7.1',
                'verbose_name_plural': '检验检测机构资质认定现场评审核查表7.1',
            },
        ),
    ]
