# Generated by Django 3.1.1 on 2020-09-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_auto_20200909_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='importtype',
            field=models.CharField(choices=[('2', '2_评审员信息表格(docx格式)'), ('0', '0_读取评审通知(docx格式)'), ('1', '1_读取评审报告(docx格式)')], default=0, max_length=1, verbose_name='导入类型'),
        ),
    ]
