# Generated by Django 3.1.1 on 2020-09-10 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_auto_20200910_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xcpshcb71',
            name='psxxbs',
        ),
        migrations.AddField(
            model_name='xcpshcb71',
            name='psxxb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.pingshenxxb', verbose_name='评审通知号'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='importtype',
            field=models.CharField(choices=[('3', '3_现场评审核查表(docx格式)'), ('1', '1_读取评审报告(docx格式)'), ('2', '2_评审员信息表格(docx格式)'), ('0', '0_读取评审通知(docx格式)')], default=0, max_length=1, verbose_name='导入类型'),
        ),
    ]
